### ISSUE TITLE
Request reviews based on new PROJECTOWNERS file

### ISSUE THREAD

**Issue by jchavarri** [ahrefs/monorobot#117]
As an improvement over [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), it'd be nice to have a file PROJECTOWNERS that matches string ids from PR labels with usernames or team names.

Some example implementation that follows CODEOWNERS could be:

```
billing @billing-owner
awesome-feature @octocats
```

Then when a PR gets labelled with `awesome-feature` label, it would ask a request from `@octocats`.

Related API: https://docs.github.com/en/rest/reference/pulls#request-reviewers-for-a-pull-request

**Comment by rr0gi** [comment]
@jchavarri this can be closed now?

**Comment by jchavarri** [comment]
Yes, thanks!
