### ISSUE TITLE
do not store branch state when status is success

### ISSUE THREAD

**Issue by Khady** [ahrefs/monorobot#159]
Over time the state.json file grows a lot with the status of staled or deleted branches. Not storing success seems like an easy optimization to limit the growth. We can assume that if a branch status isn't being stored then it's a currently being successful, basically the same as for a new branch.

```
$ rg success state.json | wc -l
130550
$ rg failure state.json | wc -l
2869
```

**Comment by thatportugueseguy** [comment]
done in https://github.com/ahrefs/monorobot/commit/42e188ad433970866ce22ed69a73340a58482d9a
